StudyHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('base.urls')),
    path('api/' , include('base.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/api/urls.py
from django.urls import path
from . import views

# Define your URL patterns here.
urlpatterns = [
    path('' , views.get_Routes),
    path('rooms/' , views.get_rooms),
    path('rooms/<str:pk>/' , views.get_room),
]

base/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

urlpatterns = [
    # User related urls
    path('user/profile/<str:pk>/', views.UserProfile , name='profile'),
    path('user/login/', views.LoginView, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/register/', views.registerView, name='register'),
    path('user/edit-user/<str:pk>/', views.edit_userView, name='edit'),
    
    # Home Page URL
    path('', views.home, name='home'),
    path('room/create-room/', views.CreateRoom, name='create-room'),
    path('room/update-room/<str:pk>/', views.UpdateRoom, name='UpdateRoom'),
    path('room/delete-room/<str:pk>/', views.DeleteRoom, name='DeleteRoom'),
    path('room/<str:pk>/', views.Room, name='room'),

    # Urls for the messages 
    # path('message/', views.addMessage , name='addMessage'),
    path('messages/<str:pk>/', views.UpdateMessage, name='update_message'),
    path('messages/delete-message/<str:pk>/', views.DeleteMessage, name='delete_message'),

    # topics urls
    path('topics/' , views.topics, name='topics'),
    path('activity/' , views.activity, name='activity'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser):
    email = models.EmailField(unique=True)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(null=True, default='avatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    def __str__(self):
        return self.username

class Topic(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Rooms(models.Model):
    host =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)  # participants in the room
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return self.name
    
class Message(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE)
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    body = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']

    def __str__(self):
        return self.body[0:100]

base/forms.py
from django.forms import ModelForm
from .models import Rooms, Message
from django.contrib.auth.models import User

class RoomForm(ModelForm):
    class Meta:
        model = Rooms
        fields = '__all__'
        exclude = ['host' , 'participants']

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')

base/api/views.py
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Rooms
from .serializers import RoomSerializer

@api_view(['GET'])
def get_Routes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/room/:id',
    ]
    return Response(routes)

@api_view(['GET'])
def get_rooms(request):
    rooms = Rooms.objects.all()
    serialized_data = RoomSerializer(rooms, many=True)
    return Response(serialized_data.data)


@api_view(['GET'])
def get_room(request , pk):
    try:
        room = Rooms.objects.get(id=pk)
    except Rooms.DoesNotExist:
        return Response({'error': 'Room not found'}, status=404)
    serialized_data = RoomSerializer(room, many=False)
    return Response(serialized_data.data) 

base/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Rooms, Topic, Message, User
from .forms import RoomForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# user models views

def UserProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.rooms_set.all()
    messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user' : user, 'room_messages' : messages, 'rooms' : rooms, 'topics' : topics}
    return render(request, 'base/user_profile.html', context)

def LoginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            user = User.objects.get(username = username)
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                messages.error(request, "username or password does not exist")
        except :
            messages.error(request, "Invalid username or password")

    context = {'page': 'login'}
    return render(request, 'base/login_register.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def registerView(request):
    if request.method == 'POST':
        data = request.POST
        if data.get('password') == data.get('confirm_password'):
            if User.objects.filter(username=data.get('username')):
                messages.error(request, 'Username already exists')
                return redirect('register')
            else:
                
                profile_picture = request.FILES.get('profile_picture')  # ✅ Get the uploaded file

                user = User.objects.create(
                    first_name=data.get('firstname'),
                    last_name=data.get('lastname'),
                    username=data.get('username'),
                    email=data.get('email'),
                    bio = data.get('bio'),
                    password=data.get('password'),
                    profile_picture=profile_picture
                )
                messages.success(request, 'Account created successfully')
                login( request, user)
                return redirect('/')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('register')

    context = {'page' : 'register'}
    return render(request, 'base/login_register.html', context)

def edit_userView(request, pk):
    user = User.objects.get(id=pk)

    try:
        if request.method == 'POST':
            if request.FILES.get('profile_picture'):
                user.profile_picture =  request.FILES.get('profile_picture')
            user.first_name = request.POST.get('firstname')
            user.last_name = request.POST.get('lastname')
            user.bio = request.POST.get('bio')
            user.email = request.POST.get('email')

            user.save()

            messages.success(request, 'Profile updated successfully')
            return redirect('/')
    except Exception as e:
        messages.error(request, str(e))

    context = {'user': user , 'page': 'register', 'updation'  : 1}
    return render(request, 'base/login_register.html', context)

# common Functions for the vuews
def save_room(request, pk= None):
    if request.method == 'POST':
        data = request.POST
        topic, create = Topic.objects.get_or_create(title = data.get('topic'))
        try:
            Room.objects.create({
                'name' : data.get('name'),
                'description' : data.get('description'),
                'topic' : topic,
                'host' : request.user,   
            })
        except:
            messages.error(request, 'Error occurred while creating room')
        if pk is not None:
            room_instance = Rooms.objects.get(id=pk)
            roomForm = RoomForm(data, instance=room_instance)
        else:
            roomForm = RoomForm(data)
        if roomForm.is_valid():
            room = roomForm.save(commit=False)
            room.host = request.user
            room.save()
            return room.id
    else:
        return False    

# Create your views here.
def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    rooms = Rooms.objects.filter(Q(topic__title__icontains=q)
                                 | Q(name__icontains=q)
                                 | Q(description__icontains=q))
    paginator = Paginator(rooms, 5)
    page_number = request.GET.get('page')
    page_rooms = paginator.get_page(page_number)
    all_topics = Topic.objects.all()
    topics_paginator = Paginator(all_topics, 4)
    topics = topics_paginator.get_page(page_number)
    messages = Message.objects.filter(room__in=page_rooms.object_list)

    context = {'rooms' : page_rooms, 'topics' : topics , 'room_messages' : messages , 'topic_count': all_topics.count()}
    return render(request, 'base/home.html', context)

def Room(request, pk):
    room = Rooms.objects.get(pk=pk)
    if request.method == 'POST':
        user = request.user
        try:
            message = Message.objects.create(
                user = user,
                room = room,
                body = request.POST.get('body')
                )
            # append the onwer of the message as a new participant 
            if room.host != user:
                room.participants.add(request.user)
            messages.success(request, 'Message sent successfully')
            return redirect('room' , pk=room.id)
        except:
            messages.error(request, 'Error occurred while creating message')
        
    # we can get the children of this room by specifying the childs name
    room_messages = room.message_set.all()
    context = {'room' : room , 'message': room_messages}
    return render(request , 'base/room.html', context)

@login_required(login_url='login')
def CreateRoom(request):
    if request.method == 'POST':
        data = request.POST
        topic, created = Topic.objects.get_or_create(title = data.get('topic'))
        try:
            Rooms.objects.create(
                name = data.get('room_name'),
                description = data.get('description'),
                topic = topic,
                host = request.user,   
            )
            return redirect('home')
        except Exception as e:

            messages.error(request, f'Error occurred while creating room\n{e}')
    context = {'topics' : Topic.objects.all()}
    return render(request, 'base/room_form.html', context)

@login_required(login_url='login')
def UpdateRoom(request, pk):
    room = Rooms.objects.get(pk=pk)
    roomForm = RoomForm(instance=room)
    if request.method == 'POST':
        topic_input = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(title= topic_input)
        room.topic = topic
        room.name = request.POST.get('room_name')
        room.description = request.POST.get('description')
        room.save()
        return redirect('/room/' + pk)
    context = {'roomForm': roomForm , 'topics' : Topic.objects.all(), 'room' : room}
    return render(request, 'base/room_form.html', context)
    
@login_required(login_url='login') 
def DeleteRoom(request, pk):
    if pk:
        room = Rooms.objects.get(pk=pk)
        if request.method == 'POST':
            room.delete()
            return HttpResponseRedirect('/')
    return render(request, 'base/delete_room.html', {'room': room})


# Messages views

# def addMessage(request):
#     if request.method == 'POST':
#         form = MessageForm(request.POST)
#         if form.is_valid():
#             message = form.save(commit=False)
#             message.user = request.user
#             message.room_id = request.POST.get('room_id')
#             message.save()
#             return redirect('room' + str(message.room_id))
#     return HttpResponseRedirect('/')

def UpdateMessage(request , pk):
    pass

@login_required(login_url='login')
def DeleteMessage(request , pk):
    message = Message.objects.get(id=pk)
    if request.method == 'POST':
        if request.user == message.user:
            message.delete()
            return redirect('room' , message.room_id)
        else:
            return HttpResponse('You are not allowed to delete this message')
    context = {'message': message}
    return render(request, 'base/delete_room.html' , context)


# topics view
def topics(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    room_count = Rooms.objects.filter(Q(topic__title__icontains=q)
                                 | Q(name__icontains=q)
                                 | Q(description__icontains=q)).count()
    topics = Topic.objects.filter(title__icontains=q)
    context = {'topics': topics, 'room_count': room_count}
    return render(request, 'base/topics.html', context)

    
def activity(request):
    rooms = Rooms.objects.all()
    messages = Message.objects.all()
    context = {'rooms': rooms, 'room_messages': messages}
    return render(request, 'base/activity.html', context)

base/templates/base/activity.html
{% extends 'base/main.html' %}
{% block content %}
    <main class="layout ">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{{ request.META.HTTP_REFERER }}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body layout-scroll">
            
            {% for message in room_messages  %}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'profile' message.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                  </div>
                  <p>
                    @{{ message.user.username }}
                    <span>{{ message.created_at | timesince }} ago</span>
                  </p>
                </a>
                <div class="roomListRoom__actions">
                  
                    {% if request.user == message.user %}
                      <a href="{% url 'delete_message' message.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                          ></path>
                        </svg>
                      </a>  
                    {% endif %}
                    
                </div>
              </div>
              <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room.name }}</a>”</p>
                <div class="activities__boxRoomContent">
                  {{ message }}
                </div>
              </div>
            </div>
  
            {% endfor %}
              
            
          </div>
        </div>
      </div>
    </main>

{% endblock content %}

base/templates/base/activity_component.html
{% load static %}

<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            {% if message.user.profile_picture %}
              <img src="{{ message.user.profile_picture.url }}" />
            {% else %}
              <img src="{% static 'images/avatar.svg' %}" />
            {% endif %}
            
          </div>
          <p>
            @{{ message.user.username }}
            <span>{{ message.created_at | timesince }} ago</span>
          </p>
        </a>
        {% if message.user == request.user %}
        <div class="roomListRoom__actions">
          <a href="#">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room.name }}</a>”</p>
        <div class="activities__boxRoomContent">
          {{ message }}
        </div>
      </div>
    </div>
    
    {% endfor %}

  </div>
  <!-- Activities End -->

base/templates/base/delete_room.html
{% extends 'base/main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{ request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" action="#" method="post">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete 
                            
                            {% if room %}
                                <a href="{% url 'room' room.id %}"> "{{ room }}"</a>  Room?
                                
                            {% elif message %}
                                <a href="{% url 'delete_message' message.id %}"> "{{ message }}" </a> Message?
                            {% endif %}
                                
                        </p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/edit-user.html
{% extends 'base/main.html' %}


{% block content %}
  

<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="profile.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
            viewBox="0 0 32 32">
            <title>arrow-left</title>
            <path
            d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
          </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                      </div>
                    </div>
                    <div class="layout__body">
                      <form class="form" action="#">
                        <div class="form__group">
                          <label for="profile_pic">Avatar</label>
                          <input id="profile_pic" name="profile_pic" type="file" />
                        </div>
                        
                        <div class="form__group">
                          <label for="username">Username</label>
                          <input id="username" name="username" type="text" placeholder="E.g. John doe" />
                        </div>
                        
                        <div class="form__group">
                          <label for="email">Email</label>
                          <input id="email" name="email" type="text" placeholder="E.g. john@email.com" />
                        </div>
                        
                        <div class="form__group">
                          <label for="user_bio">Bio</label>
                          <textarea name="user_bio" id="user_bio" placeholder="Write about yourself..."></textarea>
                        </div>
                        <div class="form__action">
                          <a class="btn btn--dark" href="index.html">Cancel</a>
                          <button class="btn btn--main" type="submit">Update</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </main>
            
{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <!-- <link rel="stylesheet" href="style.css" /> -->
    <title>StudyHub - Find study partners around the world!</title>
  </head>

  <body>
    {% include 'base/navbar.html' %}
    {% if messages %}
        
    <ul class="messages">
      {% for message in messages %}
          <li class="message message-{{ message.tags }}">
              {{ message }}
              <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
          </li>
      {% endfor %}
  </ul>
  
  
    {% endif %}
    
    {% block content %}

    {% endblock content %}
       
    <script src="{% static 'js/script.js'%}"></script>
  </body>
</html>

base/templates/base/room.html
{% extends 'base/main.html' %}

{% load static %}

{% block content %}

<main class="profile-page layout layout--2">
<div class="container">
    <!-- Room Start -->
    <div class="room">
        <div class="room__top">
            <div class="room__topLeft">
                <a href="{{ request.META.HTTP_REFERER  }}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>arrow-left</title>
                        <path
                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
        </a>
        <h3>Study Room</h3>
    </div>
    {% if room.host == request.user  %}
    <div class="room__topRight">
        <a href="{% url 'UpdateRoom' room.id %}">
            <svg
            enable-background="new 0 0 24 24"
            height="32"
            viewBox="0 0 24 24"
            width="32"
            xmlns="http://www.w3.org/2000/svg"
            >
            <title>edit</title>
              <g>
                  <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                </g>
                <g>
                    <g>
                        <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                        />
                    </g>
                    <g>
                        <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                        />
                    </g> 
                </g>
            </svg>
          </a>
          <a href="{% url 'DeleteRoom' room.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
            </svg>
        </a>
    </div>
    {% endif %}
    
    <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
    data-edit-url="profile.html">
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>ellipsis-horizontal</title>
        <path
        d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
    </path>
    <path
    d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
</path>
<path
d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
</path>
</svg>
</button> -->
</div>
<div class="room__box scroll">
    <div class="room__header scroll">
        <div class="room__info">
            <h3>{{ room.name }}</h3>
            <span>{{ room.created_at | timesince }} ago</span>
        </div>
        <div class="room__hosted">
            <p>Hosted By</p>
            <a href="{% url 'profile' room.host.id %}" class="room__author">
              <div class="avatar avatar--small">
                {% if room.host.profile_picture %}
                    <img src="{{ room.host.profile_picture.url }}" />
                {% else %}
                    <img src="{% static 'images/avatar.svg' %}" />
                {% endif %}
                
            </div>
            <span>@{{ room.host.username }}</span>
        </a>
    </div>
    <div class="room__details">
        {{ room.description }}
    </div>
    <span class="room__topics">{{ room.topic_set.all }}</span>
</div>
<div class="room__conversation">
    <div class="threads scroll">
        
        {% for msg in message %}
        <div class="thread">
            <div class="thread__top">
                <div class="thread__author">
                    <a href="{% url 'profile' msg.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                            {% if msg.user.profile_picture %}
                                <img src="{{ msg.user.profile_picture.url }}" />
                            {% else %}
                                <img src="{% static 'images/avatar.svg' %}" />
                            {% endif %}
                        </div>
                        <span>@{{ msg.user.username }}</span>
                    </a>
                    <span class="thread__date">{{ msg.created_at | timesince }} ago</span>
                </div>
                {% if request.user == msg.user %} 
                <div class="thread__delete">
                    <a href="{% url 'delete_message' msg.id %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" aria-hidden="true">
                                <title>remove</title>
                                <path
                                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                ></path>
                            </svg>
                        </a>
                </div>
                {% endif %}
            </div>
            <div class="thread__details">
                {{ msg }}
            </div>
        </div>
        {% endfor %}
        
    </div>
</div>
</div>
<div class="room__message">
    <form action="" method="post">
        {% csrf_token %}
        <input name="body" placeholder="Write your message here..." />
    </form>
</div>
</div>
<!-- Room End -->

<!--   Start -->
<div class="participants">
    <h3 class="participants__top">Participants <span>(5.3k Joined)</span></h3>
    <div class="participants__list scroll">
        {% if room.participants.all %}
        {% for participant in room.participants.all %}
        
        <a href="profile.html" class="participant">
            <div class="avatar avatar--medium">
                {% if participant.profile_picture %}
                    <img src="{{ participant.profile_picture.url }}" />
                {% else %}
                    <img src="{% static 'images/avatar.svg' %}" />
                {% endif %}
            </div>
                <p>
                    {{ participant.username }}
                    <span>@{{ participant.username }} </span>
                </p>
                </a>
                {% endfor %}
                {% endif %}
                
            </div>
        </div>
        <!--  End -->
    </div>
</main>
{% endblock content %}